def build(output_path: str, words: list[str], sort_input: bool = True) -> None: ...

class Fst:
    @staticmethod
    def open(path: str) -> Fst: ...
    def contains(self, key: str) -> bool: ...
    def fuzzy_search(
        self,
        query: str,
        max_distance: int = 1,
        metric: str = "levenshtein",
        algorithm: str = "bit-parallel",
    ) -> list[tuple[str, int]]: ...
    @property
    def num_nodes(self) -> int: ...
